Find new versions by parsing json
prometheus/golang-builder pull request #249
Opened 2024-02-21 21:11 UTC by gitperr

@SuperQ one attempt at fixing https://github.com/prometheus/golang-builder/issues/216

This should keep the current functionality as far as my testing goes. Now just getting the versions from the said json file.

What do you think?

2024-02-22 09:30 UTC, SuperQ commented on cmd/builder-bumper/main.go
> +	url := "https://go.dev/dl/?mode=json"
```suggestion
	const url = "https://go.dev/dl/?mode=json"
```

2024-02-22 09:35 UTC, SuperQ commented on cmd/builder-bumper/main.go
> +		newGoVersion := newGoVersion(availableVersionsJSON[i].Version)
Simplification?

```suggestion
		newGoVersion := newGoVersion(strings.TrimLeft("go", availableVersionsJSON[i].Version))
```

2024-02-22 15:53 UTC, gitperr commented on cmd/builder-bumper/main.go
> +	url := "https://go.dev/dl/?mode=json"
Done

2024-02-22 15:54 UTC, gitperr commented on cmd/builder-bumper/main.go
> +		newGoVersion := newGoVersion(availableVersionsJSON[i].Version)
Good idea :+1:

2024-03-08 21:09 UTC, gitperr commented
Does this need any other work, or is it good to merge?

2024-03-19 21:14 UTC, gitperr commented
@SuperQ this could be merged if there is no need for more changes

2025-03-06 11:56 UTC, fbegyn commented
Any reason for the `40` limit? Sure Go currently has no more minor releases then that, but it can grow to that count in the future.

If we have all the available versions, could we just sort them and iterate over them? The first one that fulfills `avilableVersion[i].Minor > *g.Minor` should be the lastest minor release.

2025-03-06 15:59 UTC, jan--f requested changes
This doesn't currently work.
Maybe adding a small unit test would be good?

2025-03-06 15:59 UTC, jan--f commented on cmd/builder-bumper/main.go
> +		newGoVersion := newGoVersion(strings.TrimLeft("go", availableVersionsJSON[i].Version))
```suggestion
		newGoVersion := newGoVersion(strings.TrimLeft(availableVersionsJSON[i].Version, "go"))
```

2025-03-06 18:11 UTC, gitperr commented on cmd/builder-bumper/main.go
> +		newGoVersion := newGoVersion(strings.TrimLeft("go", availableVersionsJSON[i].Version))
Thanks for the feedback. I added this fix, and some tests.

But now I am not sure where and when those tests should be run. As far as I see, the builder-bumper binary is not even being built anywhere here in this repo?

2025-03-07 15:11 UTC, jan--f commented
Thanks, mind signing all your commits with `git commit -s`?

2025-03-07 18:04 UTC, gitperr commented
> Thanks, mind signing all your commits with `git commit -s`?

Done!

2025-03-07 18:22 UTC, jan--f approved these changes

2025-03-07 18:45 UTC, SuperQ approved these changes
Thanks, sorry for taking so long to review this.

Let's see how this helps!

2025-03-07 18:46 UTC, merged